apiVersion: v1
kind: Service
metadata:
    name: "kwettercl-e07d"
    labels:
        app: "kwettercl-e07d"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kwettercl-e07d"